### PR TITLE
Now you can view rock, paper, scissors games.

### PR DESCRIPTION
**Pull request by andreistalker**

### CODE REVIEW

**Comment by mhabibi659** [comment]
Hi, I am designing a casino steam logo. Like this his logo

**Comment by andreistalker** [comment]
@mhabibi659 we are not accepting logo submissions anymore. Sorry.

**Comment by mhabibi659** [comment]
But, i already sent my contribusion on 23 march. Regarding the steem casino
logo

Pada tanggal Min, 25 Mar 2018 21.47, andreistalker <notifications@github.com>
menulis:

**Comment by andreistalker** [comment]
Then your submission has been already reviewed as we announced the winner. Thanks for participation.

**Comment by mhabibi659** [comment]
Thank you for your cooperation.

Pada tanggal Min, 25 Mar 2018 22.08, andreistalker <notifications@github.com>
menulis:

**Pull request merged**
